application:
    title: Plates Microservice
    version: 1.0

server:
    port: 8083

spring:
    application:
        name: plates-msvc
    devtools:
        restart:
            enabled: false
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: jdbc:postgresql://0.0.0.0:5432/mydatabase
        username: myuser
        password: secret
    docker:
        compose:
            enabled: 'false'

logging:
    level:
        org.hibernate.SQL: DEBUG